name: Run Pylint, Mypy and Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov # Ensure pytest-cov is installed for coverage reporting
    - name: Analyse the code with pylint
      run: |
        pylint src/ tests/ accord_demo.py mc_demo.py
    - name: Run mypy static type checker
      run: |
        mypy .
    - name: Run pytest with coverage and generate XML report
      run: |
        pytest --cov=src --cov-report=json tests/
    - name: Upload code coverage
      uses: actions/upload-artifact@v7
      with:
        name: coverage-${{ matrix.python-version }}
        path: |
          ./coverage.json
    - name: Parse coverage percentage
      id: get-coverage
      run: |
        COVERAGE=$(jq -r '.totals.percent_covered_display' coverage.json)
        echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

    - name: Update Coverage Badge
      # Only run this on the main branch so PRs don't overwrite the main badge
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 335ad3bc77d4305c53eeb8715939592e
        filename: accord-coverage.json
        label: coverage
        message: ${{ steps.get-coverage.outputs.coverage }}%
        valColorRange: ${{ steps.get-coverage.outputs.coverage }}
        maxColorRange: 90
        minColorRange: 50
